import { Button, Center } from "@mantine/core";
import Head from "next/head";
import { useRouter } from "next/navigation";

export default function Home() {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Center h={"100vh"} w={"100vw"}>
        <Button
          onClick={() => {
            router.push("/edit/1");
          }}
          variant="default"
          radius={"50"}
          size="md"
        >
          Add audio to your Video
        </Button>
      </Center>
    </>
  );
}
